"""empty message

Revision ID: 0cb51793d3bd
Revises: be9d9cc7dc31
Create Date: 2020-03-26 00:08:30.323825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb51793d3bd'
down_revision = 'be9d9cc7dc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flag', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'flag')
    # ### end Alembic commands ###
