"""empty message

Revision ID: 136b075b69b6
Revises: 70ace0068d01
Create Date: 2020-03-19 05:30:33.760654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136b075b69b6'
down_revision = '70ace0068d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('likes_liked_by_fkey', 'likes', type_='foreignkey')
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')
    op.drop_column('likes', 'post_id')
    op.drop_column('likes', 'liked_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('liked_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('likes', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('likes_post_id_fkey', 'likes', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('likes_liked_by_fkey', 'likes', 'users', ['liked_by'], ['id'])
    # ### end Alembic commands ###
