"""empty message

Revision ID: 140d2bbaf2e1
Revises: 9d29a40395cb
Create Date: 2020-04-10 14:45:19.300437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140d2bbaf2e1'
down_revision = '9d29a40395cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('use_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'use_status')
    # ### end Alembic commands ###
