"""empty message

Revision ID: 164ddd8f0685
Revises: 00152155fb67
Create Date: 2020-04-08 10:04:49.179833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164ddd8f0685'
down_revision = '00152155fb67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ads', 'products', ['product_id'], ['id'])
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.drop_column('ads', 'product_id')
    # ### end Alembic commands ###
