"""empty message

Revision ID: 177dfa4b4fa9
Revises: 27b8b0e2317e
Create Date: 2020-04-01 08:42:02.236646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177dfa4b4fa9'
down_revision = '27b8b0e2317e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_delete_hash')
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('image_delete_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
