"""empty message

Revision ID: 1b2467b960c6
Revises: 6701aac4ef1c
Create Date: 2020-04-10 14:42:05.166562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2467b960c6'
down_revision = '6701aac4ef1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('posted_at', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'posted_at')
    # ### end Alembic commands ###
