"""empty message

Revision ID: 2b74116edaaa
Revises: e71ae591f042
Create Date: 2020-04-10 14:39:46.898104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b74116edaaa'
down_revision = 'e71ae591f042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('posted_at', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'posted_at')
    # ### end Alembic commands ###
