"""empty message

Revision ID: 392f1acc5929
Revises: 8e5813546b03
Create Date: 2020-04-25 10:25:52.238232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392f1acc5929'
down_revision = '8e5813546b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'posted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posted_at', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
