"""empty message

Revision ID: 3df5e27b73ca
Revises: 96fc63b3e372
Create Date: 2020-05-14 12:33:33.763422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df5e27b73ca'
down_revision = '96fc63b3e372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'posted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posted_at', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
