"""empty message

Revision ID: 45019418bb80
Revises: 3df5e27b73ca
Create Date: 2020-05-14 12:33:59.376197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45019418bb80'
down_revision = '3df5e27b73ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posted_at', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'posted_at')
    # ### end Alembic commands ###
