"""empty message

Revision ID: 5153d7d3440f
Revises: 0965da7d9d6b
Create Date: 2020-03-25 01:06:26.502769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5153d7d3440f'
down_revision = '0965da7d9d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('created_at', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
