"""empty message

Revision ID: 524ac5c5c0d0
Revises: b70bbce29fb2
Create Date: 2020-05-01 14:48:36.099049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524ac5c5c0d0'
down_revision = 'b70bbce29fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('at', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'at')
    # ### end Alembic commands ###
