"""empty message

Revision ID: 52fc9bbb52fc
Revises: ab2a805132eb
Create Date: 2020-04-14 12:56:44.637495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fc9bbb52fc'
down_revision = 'ab2a805132eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ads', 'shops', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.drop_column('ads', 'shop_id')
    # ### end Alembic commands ###
