"""empty message

Revision ID: 5319d5bb2bfa
Revises: becd3f66e1ed
Create Date: 2020-01-14 22:43:36.838152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5319d5bb2bfa'
down_revision = 'becd3f66e1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('login_times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_times')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
