"""empty message

Revision ID: 5d74095ee99e
Revises: 7be88de52de2
Create Date: 2020-05-02 14:57:09.865557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d74095ee99e'
down_revision = '7be88de52de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    op.drop_table('reports')
    op.drop_column('feedback', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['by'], ['users.id'], name='reports_by_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='reports_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reports_pkey')
    )
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('flag', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='countries_pkey')
    )
    # ### end Alembic commands ###
