"""empty message

Revision ID: 61804220190c
Revises: d726e6e63822
Create Date: 2020-03-22 09:02:02.174474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61804220190c'
down_revision = 'd726e6e63822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_image', sa.String(length=100), nullable=True))
    op.add_column('comments', sa.Column('user_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'user_name')
    op.drop_column('comments', 'user_image')
    # ### end Alembic commands ###
