"""empty message

Revision ID: 66c6afefa383
Revises: 8640cf796d39
Create Date: 2020-04-06 11:10:01.762375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c6afefa383'
down_revision = '8640cf796d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'user_image')
    op.drop_column('comments', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('user_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
