"""empty message

Revision ID: 6701aac4ef1c
Revises: 2b74116edaaa
Create Date: 2020-04-10 14:41:13.523687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6701aac4ef1c'
down_revision = '2b74116edaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'posted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('posted_at', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
