"""empty message

Revision ID: 6a5ffa135d6b
Revises: b59bb3b170d9
Create Date: 2020-05-01 14:42:38.834966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5ffa135d6b'
down_revision = 'b59bb3b170d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'rating')
    # ### end Alembic commands ###
