"""empty message

Revision ID: 7be88de52de2
Revises: 95d594925919
Create Date: 2020-05-02 09:00:49.991920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be88de52de2'
down_revision = '95d594925919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'message')
    # ### end Alembic commands ###
