"""empty message

Revision ID: 7f08f2098ec9
Revises: af4048a5f01e
Create Date: 2020-04-13 09:32:14.505383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f08f2098ec9'
down_revision = 'af4048a5f01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('posted_at', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'posted_at')
    # ### end Alembic commands ###
