"""empty message

Revision ID: 8333a3a1dee7
Revises: fae37575b338
Create Date: 2020-04-08 10:08:24.497996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8333a3a1dee7'
down_revision = 'fae37575b338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_on', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
