"""empty message

Revision ID: 8640cf796d39
Revises: b73ec8bf1415
Create Date: 2020-04-02 09:42:34.462932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8640cf796d39'
down_revision = 'b73ec8bf1415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img_del_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_img', sa.String(length=255), nullable=True))
    op.drop_column('users', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_img')
    op.drop_column('users', 'img_del_hash')
    # ### end Alembic commands ###
