"""empty message

Revision ID: 8c39c409e61e
Revises: d3473023ef8b
Create Date: 2020-04-08 18:13:01.776797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c39c409e61e'
down_revision = 'd3473023ef8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('created_on', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'created_on')
    # ### end Alembic commands ###
