"""empty message

Revision ID: 96fc63b3e372
Revises: 5d74095ee99e
Create Date: 2020-05-02 14:57:28.313106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fc63b3e372'
down_revision = '5d74095ee99e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'rating')
    # ### end Alembic commands ###
