"""empty message

Revision ID: 978b6020dc19
Revises: ccdf0f47e054
Create Date: 2020-03-08 16:39:34.423792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978b6020dc19'
down_revision = 'ccdf0f47e054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('on', sa.Integer(), nullable=True),
    sa.Column('by', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['on'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
