"""empty message

Revision ID: 9c29089be11b
Revises: 8333a3a1dee7
Create Date: 2020-04-08 10:08:38.847360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c29089be11b'
down_revision = '8333a3a1dee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_on', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'created_on')
    # ### end Alembic commands ###
