"""empty message

Revision ID: 9d29a40395cb
Revises: 1b2467b960c6
Create Date: 2020-04-10 14:43:25.019154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d29a40395cb'
down_revision = '1b2467b960c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'use_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('use_status', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
