"""empty message

Revision ID: 9d715043ca94
Revises: 8c39c409e61e
Create Date: 2020-04-08 23:46:23.135998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d715043ca94'
down_revision = '8c39c409e61e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'description')
    # ### end Alembic commands ###
