"""empty message

Revision ID: 9fc171918e4a
Revises: a35f0685aa74
Create Date: 2020-03-26 08:52:13.588085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc171918e4a'
down_revision = 'a35f0685aa74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'flag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flag', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
