"""empty message

Revision ID: a1d51ce0b613
Revises: 52fc9bbb52fc
Create Date: 2020-04-14 23:59:21.663721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d51ce0b613'
down_revision = '52fc9bbb52fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productimages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.Column('del_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productimages')
    # ### end Alembic commands ###
