"""empty message

Revision ID: a64ee70a0978
Revises: 2df9b86f09a3
Create Date: 2020-04-08 18:10:49.258808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64ee70a0978'
down_revision = '2df9b86f09a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('created_on', sa.String(length=25), nullable=True))
    op.drop_column('shops', 'posted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('posted_at', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_column('shops', 'created_on')
    # ### end Alembic commands ###
