"""empty message

Revision ID: af4048a5f01e
Revises: 259e9a2d9e9a
Create Date: 2020-04-13 09:31:57.843960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4048a5f01e'
down_revision = '259e9a2d9e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'posted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('posted_at', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
