"""empty message

Revision ID: b73ec8bf1415
Revises: 177dfa4b4fa9
Create Date: 2020-04-01 14:48:58.350414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73ec8bf1415'
down_revision = '177dfa4b4fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photoimages', sa.Column('imageUrl', sa.String(length=255), nullable=True))
    op.drop_column('photoimages', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photoimages', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('photoimages', 'imageUrl')
    # ### end Alembic commands ###
