"""empty message

Revision ID: b8deff8c07d0
Revises: 164ddd8f0685
Create Date: 2020-04-08 10:05:09.177186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8deff8c07d0'
down_revision = '164ddd8f0685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###
