"""empty message

Revision ID: b8ee661bb356
Revises: 392f1acc5929
Create Date: 2020-04-25 10:26:18.218850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ee661bb356'
down_revision = '392f1acc5929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posted_at', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'posted_at')
    # ### end Alembic commands ###
