"""empty message

Revision ID: be9d9cc7dc31
Revises: 5153d7d3440f
Create Date: 2020-03-25 01:06:45.534959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9d9cc7dc31'
down_revision = '5153d7d3440f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('created_at', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'created_at')
    # ### end Alembic commands ###
