"""empty message

Revision ID: ccdf0f47e054
Revises: d34ba65b79af
Create Date: 2020-03-07 18:02:25.973654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdf0f47e054'
down_revision = 'd34ba65b79af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'country')
    # ### end Alembic commands ###
