"""empty message

Revision ID: d3473023ef8b
Revises: a64ee70a0978
Create Date: 2020-04-08 18:12:45.878595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3473023ef8b'
down_revision = 'a64ee70a0978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('created_on', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
