"""empty message

Revision ID: d726e6e63822
Revises: 6ca7fa211431
Create Date: 2020-03-19 05:34:26.165654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd726e6e63822'
down_revision = '6ca7fa211431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('liked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'liked_at')
    # ### end Alembic commands ###
