"""empty message

Revision ID: f388f56b0c23
Revises: 25640f754903
Create Date: 2020-05-22 16:13:56.522495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f388f56b0c23'
down_revision = '25640f754903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posted_at', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'posted_at')
    # ### end Alembic commands ###
