"""empty message

Revision ID: f9710311a47f
Revises: b8ee661bb356
Create Date: 2020-04-25 10:37:44.670604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9710311a47f'
down_revision = 'b8ee661bb356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shopOwner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shopOwner', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
