"""empty message

Revision ID: f9abd2fe7e67
Revises: 978b6020dc19
Create Date: 2020-03-08 18:27:59.309202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9abd2fe7e67'
down_revision = '978b6020dc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('reports_on_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'posts', ['post_id'], ['id'])
    op.drop_column('reports', 'on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('on', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_on_fkey', 'reports', 'posts', ['on'], ['id'])
    op.drop_column('reports', 'post_id')
    # ### end Alembic commands ###
